name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.5
          - 8.4
          - 8.3
          - 8.2

    steps:
      - uses: actions/checkout@v6

      - name: Installing PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit -c tests
